# MySQL 数据库连接配置
#spring:
#  datasource:
#    url: jdbc:mysql://192.168.31.48:3306/ast-sql?useSSL=false&serverTimezone=UTC
#    username: root
#    password: mysql
#    driver-class-name: com.mysql.cj.jdbc.Driver

spring:
  datasource:
    url: jdbc:dm://192.168.31.48:5237/AST-SQL?zeroDateTimeBehavior=convertToNull&useUnicode=true&characterEncoding=utf-8
    username: SYSDBA
    password: xiamuLala123
    driver-class-name: dm.jdbc.driver.DmDriver # Dameng 数据库驱动类名


# 日志配置，用于输出SQL日志
logging:
  level:
    # 你的应用主包，设置为 DEBUG 可以看到更详细的业务逻辑日志
    icu.xiamu: DEBUG
    # MyBatis 相关的日志
    # 设置为 DEBUG 可以看到 SQL 语句和参数
    # 设置为 TRACE 可以看到更详细的结果集映射等信息
    org.mybatis.spring: DEBUG
    org.apache.ibatis: DEBUG
    # 如果想看到底层的 JDBC 驱动日志，包括连接信息等
    java.sql: DEBUG
    com.mysql.cj.jdbc: DEBUG

# MyBatis 配置
mybatis:
  mapper-locations: "classpath*:mapper/*.xml"
  type-aliases-package: "icu.xiamu.domain" # 注意这里我已经帮你更正为你的包名 icu.xiamu