spring:
  application:
    name: spring-cache
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.1.100:3306/spring-cache?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
  jpa:
    database: MySQL
#    database-platform: org.hibernate.dialect.MySQL5Dialect
    show-sql: true
    hibernate:
      ddl-auto: update
  cache:
    type: caffeine
    caffeine:
      spec: initialCapacity=100,maximumSize=500,expireAfterWrite=600s

server:
  port: 8888
